# Generated by Django 3.1.7 on 2021-03-03 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='isorder',
            field=models.BooleanField(default=False, verbose_name='是否顺序执行'),
        ),
        migrations.CreateModel(
            name='Testcaselist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runno', models.IntegerField(verbose_name='顺序号')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.testcase', verbose_name='测试用例')),
                ('testsuite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.testsuite', verbose_name='测试套件')),
            ],
            options={
                'verbose_name_plural': '顺序运行用例',
            },
        ),
    ]
