# Generated by Django 3.1.7 on 2021-03-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_auto_20210303_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='isrun',
        ),
        migrations.AddField(
            model_name='testcase',
            name='isValid',
            field=models.CharField(choices=[('Y', '是'), ('N', '否')], default='Y', max_length=10, verbose_name='是否有效'),
        ),
    ]
