# Generated by Django 3.1.7 on 2021-03-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_auto_20210306_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='requestdata',
            field=models.TextField(blank=True, default='{}', max_length=1000, null=True, verbose_name='请求报文'),
        ),
    ]
