# Generated by Django 3.1.7 on 2021-03-13 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apitest', '0004_auto_20210308_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testbatch',
            name='ctime',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='ctime',
        ),
        migrations.AddField(
            model_name='api',
            name='creater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='api',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='apigroup',
            name='creater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apigroup',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='apigroup',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='func',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='creater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='testbatch',
            name='creater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testbatch',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='testbatch',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='testcasegroup',
            name='creater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcasegroup',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='testcasegroup',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='assertparam',
            name='mode',
            field=models.CharField(choices=[('assert_equal', 'equils'), ('assert_contains', 'contains'), ('assert_regex_match', 'regex_match'), ('assert_json_contains', 'jsoncontains'), ('assert_jsonmatch', 'jsonmatch')], default='eq', max_length=100, verbose_name='模式'),
        ),
        migrations.CreateModel(
            name='DebugTalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, max_length=10000, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apitest.project')),
            ],
            options={
                'verbose_name_plural': '驱动py文件',
            },
        ),
    ]
