# Generated by Django 3.1.7 on 2021-03-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0005_auto_20210313_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assertparam',
            name='mode',
            field=models.CharField(choices=[('assert_equal', 'equils'), ('assert_contains', 'contains'), ('assert_regex_match', 'regex_match')], default='eq', max_length=100, verbose_name='模式'),
        ),
    ]
