# Generated by Django 3.1.7 on 2021-03-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0006_auto_20210313_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='code',
        ),
    ]
