# Generated by Django 3.1.7 on 2021-02-25 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0006_auto_20210225_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestparam',
            name='api',
        ),
        migrations.AlterField(
            model_name='requestparam',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.testcase'),
        ),
    ]
