# Generated by Django 3.1.7 on 2021-02-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0007_auto_20210225_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assertparam',
            name='mode',
            field=models.CharField(choices=[('eq', 'equils'), ('in', 'contains')], default='eq', max_length=10, verbose_name='模式'),
        ),
    ]
