# Generated by Django 3.1.7 on 2021-02-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0008_auto_20210225_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='assertval',
            name='type',
            field=models.CharField(choices=[('str', 'string'), ('int', 'int'), ('bool', 'bool')], default='str', max_length=10, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='reqquestval',
            name='type',
            field=models.CharField(choices=[('str', 'string'), ('int', 'int'), ('bool', 'bool')], default='str', max_length=10, verbose_name='类型'),
        ),
    ]
