# Generated by Django 3.1.7 on 2021-03-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0008_auto_20210318_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbatch',
            name='args',
            field=models.ManyToManyField(blank=True, related_name='Argument_batch', to='apitest.Argument', verbose_name='pytest运行参数'),
        ),
        migrations.AddField(
            model_name='testbatch',
            name='reruns',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='失败重跑次数'),
        ),
        migrations.AddField(
            model_name='testbatch',
            name='reruns_delay',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='重跑间隔时间'),
        ),
    ]
