# Generated by Django 3.1.7 on 2021-03-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0009_auto_20210318_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testbatch',
            old_name='batchno',
            new_name='name',
        ),
    ]
