# Generated by Django 3.1.7 on 2021-02-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0009_auto_20210225_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='caseno',
            field=models.CharField(default=111, max_length=100),
            preserve_default=False,
        ),
    ]
