# Generated by Django 3.1.7 on 2021-02-25 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0010_testcase_caseno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assertparam',
            name='paramval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.assertval'),
        ),
    ]
