# Generated by Django 3.1.7 on 2021-03-21 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apitest', '0010_auto_20210318_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jenkinsreport',
        ),
        migrations.AlterField(
            model_name='testbatch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='批次名称'),
        ),
        migrations.AlterField(
            model_name='testbatch',
            name='runtime',
            field=models.DateTimeField(null=True, verbose_name='运行时间'),
        ),
        migrations.AlterField(
            model_name='testbatch',
            name='testsuite',
            field=models.ManyToManyField(related_name='TESTSUITE_batch', to='apitest.TESTSUITE', verbose_name='测试套件'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='runner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='运行人'),
        ),
    ]
