# Generated by Django 3.1.7 on 2021-03-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0010_auto_20210318_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testbatch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='批次名称'),
        ),
        migrations.AlterField(
            model_name='testbatch',
            name='runtime',
            field=models.DateTimeField(null=True, verbose_name='运行时间'),
        ),
        migrations.AlterField(
            model_name='testbatch',
            name='testsuite',
            field=models.ManyToManyField(related_name='TESTSUITE_batch', to='apitest.TESTSUITE', verbose_name='测试套件'),
        ),
    ]
