# Generated by Django 3.1.7 on 2021-03-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0011_auto_20210321_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jenkinsreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='序列号')),
                ('url', models.URLField(max_length=100, null=True)),
                ('duration', models.DurationField(null=True, verbose_name='运行时长')),
                ('runtime', models.DateTimeField(null=True, verbose_name='运行时间')),
                ('result', models.CharField(max_length=10, null=True, verbose_name='运行结果')),
                ('output', models.TextField(max_length=10000, null=True, verbose_name='运行日志')),
                ('receivetime', models.DateTimeField(auto_now=True, null=True, verbose_name='接收时间')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.testbatch', verbose_name='运行批次')),
            ],
            options={
                'verbose_name_plural': 'Jenkins运行结果',
            },
        ),
    ]
