# Generated by Django 3.1.7 on 2021-02-25 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0011_auto_20210225_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerparam',
            name='paramkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.headerkey'),
        ),
        migrations.AlterField(
            model_name='headerparam',
            name='paramval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.headerval'),
        ),
    ]
