# Generated by Django 3.1.7 on 2021-03-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0012_jenkinsreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testreport',
            name='runner',
        ),
    ]
