# Generated by Django 3.1.7 on 2021-02-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0012_auto_20210225_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqquestval',
            name='type',
            field=models.CharField(choices=[('str', 'string'), ('int', 'int')], default='str', max_length=10, verbose_name='类型'),
        ),
    ]
