# Generated by Django 3.1.7 on 2021-02-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0014_auto_20210225_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='value',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reqquestval',
            name='type',
            field=models.CharField(choices=[('str', 'string'), ('int', 'int'), ('True', 'True'), ('False', 'False')], default='str', max_length=10, verbose_name='类型'),
        ),
    ]
