# Generated by Django 3.1.7 on 2021-02-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0015_auto_20210225_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assertval',
            name='type',
            field=models.CharField(choices=[('str', 'string'), ('int', 'int'), ('True', 'True'), ('False', 'False')], default='str', max_length=10, verbose_name='类型'),
        ),
    ]
