# Generated by Django 3.1.7 on 2021-03-23 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0015_auto_20210323_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='teardownfunc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teardownfunc_suite', to='apitest.func', verbose_name='请求后置方法'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='setupfunc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setupfunc_suite', to='apitest.func', verbose_name='请求前置方法'),
        ),
    ]
