# Generated by Django 3.1.7 on 2021-02-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0016_auto_20210225_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuite',
            name='failreruntime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
