# Generated by Django 3.1.7 on 2021-02-26 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0018_auto_20210226_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.project'),
        ),
    ]
