# Generated by Django 3.1.7 on 2021-02-26 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0019_testsuite_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuite',
            name='failgoon',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='failrerun',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='failreruntime',
        ),
    ]
