# Generated by Django 3.1.7 on 2021-02-26 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0020_auto_20210226_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runparam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField(max_length=100000, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.testcase')),
            ],
        ),
        migrations.CreateModel(
            name='Runbatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchno', models.CharField(max_length=100)),
                ('batchcase', models.ManyToManyField(related_name='Testcase_batch', to='apitest.Testcase')),
            ],
        ),
    ]
