# Generated by Django 3.1.7 on 2021-02-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0021_runbatch_runparam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('DELETE', 'DELETE')], max_length=10),
        ),
    ]
