# Generated by Django 3.1.7 on 2021-02-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0022_auto_20210226_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testbatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchno', models.CharField(max_length=100)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('runtime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='testsuite',
            name='runtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Runbatch',
        ),
        migrations.AddField(
            model_name='testbatch',
            name='batchobs',
            field=models.ManyToManyField(related_name='TESTSUITE_batch', to='apitest.TESTSUITE'),
        ),
    ]
