# Generated by Django 3.1.7 on 2021-02-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0023_auto_20210226_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
