# Generated by Django 3.1.7 on 2021-02-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0025_apigroup_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='stfunc',
            field=models.ManyToManyField(blank=True, related_name='api_stfunc', to='apitest.FUNC'),
        ),
        migrations.AddField(
            model_name='api',
            name='tdfunc',
            field=models.ManyToManyField(blank=True, related_name='api_tdfunc', to='apitest.FUNC'),
        ),
    ]
