# Generated by Django 3.1.7 on 2021-02-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0026_auto_20210226_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='stfunc',
        ),
        migrations.RemoveField(
            model_name='api',
            name='tdfunc',
        ),
    ]
