# Generated by Django 3.1.7 on 2021-02-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0030_auto_20210227_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreport',
            name='file',
            field=models.FileField(default='report/html/index.html', upload_to='report'),
        ),
    ]
