# Generated by Django 3.1.7 on 2021-02-27 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0031_testreport_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasegroup',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.project'),
        ),
    ]
