# Generated by Django 3.1.7 on 2021-02-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0032_testcasegroup_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='stfunc',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='tdfunc',
        ),
    ]
