# Generated by Django 3.1.7 on 2021-02-28 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0033_auto_20210228_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='setupfunc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.func'),
        ),
    ]
