# Generated by Django 3.1.7 on 2021-02-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0034_testcase_setupfunc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='func',
            name='args',
        ),
        migrations.AddField(
            model_name='func',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
