# Generated by Django 3.1.7 on 2021-03-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0038_auto_20210301_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiurl', models.CharField(max_length=100)),
                ('reqdata', models.CharField(max_length=100, null=True)),
                ('repdata', models.CharField(max_length=10000, null=True)),
                ('reqtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
