# Generated by Django 3.1.7 on 2021-03-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0039_postdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arguments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('testsuite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.testsuite')),
            ],
        ),
    ]
