# Generated by Django 3.1.7 on 2021-03-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0040_arguments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Arguments',
        ),
        migrations.AddField(
            model_name='testsuite',
            name='args',
            field=models.ManyToManyField(blank=True, null=True, related_name='Argument_suites', to='apitest.Argument'),
        ),
    ]
