# Generated by Django 3.1.7 on 2021-03-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0041_auto_20210301_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='reruns',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='reruns_delay',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
