# Generated by Django 3.1.7 on 2021-03-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0042_auto_20210301_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuite',
            name='reruns',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='reruns_delay',
        ),
        migrations.AddField(
            model_name='testsuite',
            name='isrerun',
            field=models.BooleanField(default=False),
        ),
    ]
