# Generated by Django 3.1.7 on 2021-03-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0044_auto_20210301_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jenkinsreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testno', models.IntegerField()),
                ('url', models.CharField(max_length=100, null=True)),
                ('result', models.CharField(choices=[('Y', '成功'), ('N', '失败')], max_length=10, null=True, verbose_name='运行结果')),
                ('output', models.TextField(max_length=10000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jenkins测试结果',
            },
        ),
    ]
