# Generated by Django 3.1.7 on 2021-03-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0045_jenkinsreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenkinsreport',
            name='url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
