# Generated by Django 3.1.7 on 2021-03-02 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apitest', '0047_auto_20210302_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assertparam',
            options={'verbose_name_plural': '校验参数'},
        ),
        migrations.AlterModelOptions(
            name='headerparam',
            options={'verbose_name_plural': '自定义请求头'},
        ),
        migrations.AlterModelOptions(
            name='requestparam',
            options={'verbose_name_plural': '请求参数'},
        ),
        migrations.RenameField(
            model_name='runparam',
            old_name='value',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='runparam',
            old_name='key',
            new_name='param',
        ),
        migrations.AlterField(
            model_name='api',
            name='code',
            field=models.CharField(max_length=100, verbose_name='代码'),
        ),
        migrations.AlterField(
            model_name='api',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='api',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.apigroup', verbose_name='所属分组'),
        ),
        migrations.AlterField(
            model_name='api',
            name='header',
            field=models.ManyToManyField(related_name='header_apis', to='apitest.Header', verbose_name='请求头'),
        ),
        migrations.AlterField(
            model_name='api',
            name='isValid',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='api',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('DELETE', 'DELETE')], max_length=10, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='api',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='assertparam',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='assertparam',
            name='paramkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.assertkey', verbose_name='参数'),
        ),
        migrations.AlterField(
            model_name='assertparam',
            name='paramval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.assertval', verbose_name='值'),
        ),
        migrations.AlterField(
            model_name='headerparam',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='headerparam',
            name='paramkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.headerkey', verbose_name='参数'),
        ),
        migrations.AlterField(
            model_name='headerparam',
            name='paramval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.headerval', verbose_name='值'),
        ),
        migrations.AlterField(
            model_name='requestparam',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='requestparam',
            name='paramkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.reqquestkey', verbose_name='参数'),
        ),
        migrations.AlterField(
            model_name='requestparam',
            name='paramval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.reqquestval', verbose_name='值'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='api',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.api', verbose_name='测试接口'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='baseurl',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.baseurl', verbose_name='环境地址'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='callfunc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.callfunc', verbose_name='运行方法'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='casename',
            field=models.CharField(max_length=100, verbose_name='用例名称'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='caseno',
            field=models.CharField(max_length=100, verbose_name='用例编号'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='datamode',
            field=models.CharField(choices=[('JSON', 'JSON'), ('FORM-DATA', 'FORM-DATA')], max_length=10, verbose_name='请求参数类型'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.testcasegroup', verbose_name='所属分组'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='requestdata',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='请求报文'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='responsedata',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='响应报文'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='runtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='运行时间'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='setupfunc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.func', verbose_name='请求前置方法'),
        ),
    ]
