# Generated by Django 3.1.7 on 2021-03-02 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apitest', '0048_auto_20210302_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runparam',
            options={'verbose_name_plural': '响应保存'},
        ),
        migrations.AlterField(
            model_name='api',
            name='header',
            field=models.ManyToManyField(blank=True, null=True, related_name='header_apis', to='apitest.Header', verbose_name='请求头'),
        ),
        migrations.AlterField(
            model_name='runparam',
            name='description',
            field=models.TextField(max_length=100000, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='runparam',
            name='param',
            field=models.CharField(max_length=100, verbose_name='参数'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='callfunc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.callfunc', verbose_name='自定义运行方法'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='errors',
            field=models.TextField(max_length=10000, null=True, verbose_name='异常信息'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='fail',
            field=models.IntegerField(blank=True, null=True, verbose_name='失败用例数量'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='failcase',
            field=models.ManyToManyField(blank=True, related_name='case_failcase', to='apitest.Testcase', verbose_name='失败用例'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='file',
            field=models.FileField(default='report/html/index.html', upload_to='report', verbose_name='报告文件'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='reportname',
            field=models.CharField(max_length=100, verbose_name='报告名称'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='运行人'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='suc',
            field=models.IntegerField(blank=True, null=True, verbose_name='成功用例数量'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='succase',
            field=models.ManyToManyField(blank=True, related_name='case_succase', to='apitest.Testcase', verbose_name='成功用例'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='testcases',
            field=models.ManyToManyField(related_name='case_report', to='apitest.Testcase', verbose_name='测试用例'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='testnum',
            field=models.IntegerField(verbose_name='用例数量'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='testsuite',
            field=models.ManyToManyField(related_name='suite_report', to='apitest.TESTSUITE', verbose_name='测试套件'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='testtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='测试时间'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='args',
            field=models.ManyToManyField(blank=True, null=True, related_name='Argument_suites', to='apitest.Argument', verbose_name='pytest运行参数'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='baseurl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.baseurl', verbose_name='环境地址'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='callfunc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.callfunc', verbose_name='自定义运行方法'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='case',
            field=models.ManyToManyField(blank=True, null=True, related_name='case_suites', to='apitest.Testcase', verbose_name='用例集'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='name',
            field=models.CharField(max_length=100, verbose_name='套件名称'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='reruns',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='失败重跑次数'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='reruns_delay',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='重跑间隔时间'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='runtime',
            field=models.DateTimeField(null=True, verbose_name='运行时间'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='setupfunc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.func', verbose_name='请求前置方法'),
        ),
    ]
