# Generated by Django 3.1.7 on 2021-03-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0050_testcaselist'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='isorder',
            field=models.BooleanField(default=False),
        ),
    ]
