# Generated by Django 3.1.7 on 2021-03-03 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0051_testsuite_isorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcaselist',
            options={'verbose_name_plural': '顺序运行用例'},
        ),
        migrations.AlterField(
            model_name='testcaselist',
            name='runno',
            field=models.IntegerField(verbose_name='顺序号'),
        ),
        migrations.AlterField(
            model_name='testcaselist',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.testcase', verbose_name='测试用例'),
        ),
        migrations.AlterField(
            model_name='testcaselist',
            name='testsuite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.testsuite', verbose_name='测试套件'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='isorder',
            field=models.BooleanField(default=False, verbose_name='是否顺序执行'),
        ),
    ]
