# Generated by Django 3.1.7 on 2021-03-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0052_auto_20210303_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='isrun',
            new_name='isValid',
        ),
    ]
