# Generated by Django 3.1.7 on 2021-03-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0053_auto_20210303_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='sleeptime',
            field=models.IntegerField(default=0, verbose_name='运行延时'),
        ),
    ]
