# Generated by Django 3.1.7 on 2021-03-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0054_testsuite_sleeptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='isValid',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
    ]
