# Generated by Django 3.1.7 on 2021-03-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0056_auto_20210308_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assertparam',
            name='mode',
            field=models.CharField(choices=[('assert_equal', 'equils'), ('assert_contains', 'contains'), ('assert_regex_match', 'regex_match'), ('assert_json_contains', 'jsoncontains'), ('assert_jsonmatch', 'jsonmatch')], default='eq', max_length=100, verbose_name='模式'),
        ),
    ]
