# Generated by Django 3.1.7 on 2021-03-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0057_auto_20210309_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='creater',
        ),
    ]
