# Generated by Django 3.1.7 on 2021-03-11 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apitest', '0058_remove_testcase_creater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testbatch',
            name='ctime',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='ctime',
        ),
        migrations.AddField(
            model_name='api',
            name='creater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='apigroup',
            name='creater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apigroup',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='func',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='creater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='testbatch',
            name='creater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testbatch',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='creater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcasegroup',
            name='creater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcasegroup',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
