# Generated by Django 3.1.7 on 2021-03-11 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0059_auto_20210311_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebugTalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FilePathField()),
                ('content', models.TextField(max_length=10000)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apitest.project')),
            ],
            options={
                'verbose_name_plural': '驱动py文件',
            },
        ),
    ]
