# Generated by Django 3.1.7 on 2021-03-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0061_auto_20210311_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debugtalk',
            name='content',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
