# Generated by Django 3.1.7 on 2021-03-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0062_auto_20210312_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='apigroup',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='testbatch',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='testcasegroup',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='debugtalk',
            name='content',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
