# Generated by Django 3.1.7 on 2021-03-22 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0064_auto_20210318_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jenkinsreport',
            options={'verbose_name_plural': 'Jenkins运行结果'},
        ),
        migrations.RemoveField(
            model_name='jenkinsreport',
            name='testno',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='runner',
        ),
        migrations.AddField(
            model_name='jenkinsreport',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.testbatch', verbose_name='运行批次'),
        ),
        migrations.AddField(
            model_name='jenkinsreport',
            name='duration',
            field=models.DurationField(null=True, verbose_name='运行时长'),
        ),
        migrations.AddField(
            model_name='jenkinsreport',
            name='number',
            field=models.IntegerField(default=1, verbose_name='序列号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jenkinsreport',
            name='receivetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='接收时间'),
        ),
        migrations.AddField(
            model_name='jenkinsreport',
            name='runtime',
            field=models.DateTimeField(null=True, verbose_name='运行时间'),
        ),
        migrations.AlterField(
            model_name='jenkinsreport',
            name='output',
            field=models.TextField(max_length=10000, null=True, verbose_name='运行日志'),
        ),
        migrations.AlterField(
            model_name='jenkinsreport',
            name='result',
            field=models.CharField(max_length=10, null=True, verbose_name='运行结果'),
        ),
        migrations.AlterField(
            model_name='testbatch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='批次名称'),
        ),
        migrations.AlterField(
            model_name='testbatch',
            name='runtime',
            field=models.DateTimeField(null=True, verbose_name='运行时间'),
        ),
        migrations.AlterField(
            model_name='testbatch',
            name='testsuite',
            field=models.ManyToManyField(related_name='TESTSUITE_batch', to='apitest.TESTSUITE', verbose_name='测试套件'),
        ),
    ]
