# Generated by Django 3.1.7 on 2021-03-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0066_auto_20210323_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postdata',
        ),
        migrations.DeleteModel(
            name='Runparam',
        ),
    ]
