# Generated by Django 3.1.7 on 2021-03-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0067_auto_20210325_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sonpj',
        ),
        migrations.AlterField(
            model_name='assertparam',
            name='mode',
            field=models.CharField(choices=[('assert_equal', 'equils'), ('assert_contains', 'contains'), ('assert_regex_match', 'regex_match'), ('assert_json_contains', 'jsoncontains'), ('assert_jsonmatch', 'jsonmatch')], default='assert_equal', max_length=100, verbose_name='模式'),
        ),
        migrations.AlterField(
            model_name='project',
            name='banben',
            field=models.CharField(max_length=100, null=True, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='项目名称'),
        ),
    ]
