# Generated by Django 3.1.7 on 2021-03-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0068_auto_20210330_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assertparam',
            name='mode',
            field=models.CharField(choices=[('assert_equal', 'equils'), ('assert_not_equal', 'not_equal'), ('assert_string_equals', 'string_equals'), ('assert_startswith', 'startswith'), ('assert_endswith', 'endswith'), ('assert_contained_by', 'contained_by'), ('assert_type_match', 'type_match'), ('assert_length_equal', 'length_equal'), ('assert_length_equal', 'length_equal'), ('assert_contains', 'contains'), ('assert_regex_match', 'regex_match'), ('assert_json_contains', 'jsoncontains'), ('assert_jsonmatch', 'jsonmatch')], default='assert_equal', max_length=100, verbose_name='模式'),
        ),
    ]
