# Generated by Django 3.1.7 on 2021-04-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0071_auto_20210401_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='requesttype',
            field=models.CharField(choices=[('1', '异步'), ('2', '同步')], default=2, max_length=10, verbose_name='requesttype'),
            preserve_default=False,
        ),
    ]
