# Generated by Django 3.1.7 on 2021-04-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0074_auto_20210401_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='beforecase',
        ),
    ]
