# Generated by Django 3.1.7 on 2021-04-12 10:07

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0076_auto_20210409_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='isValid',
            field=simplepro.components.fields.SwitchField(default=True, verbose_name='是否有效'),
        ),
    ]
