# Generated by Django 3.1.7 on 2021-04-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0077_auto_20210412_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='isValid',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
    ]
