# Generated by Django 3.1.7 on 2021-04-13 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0078_auto_20210412_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuite',
            name='args',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='baseurl',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='callfunc',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='reruns',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='reruns_delay',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='setupfunc',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='sleeptime',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='teardownfunc',
        ),
    ]
