# Generated by Django 3.1.7 on 2021-04-13 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0079_auto_20210413_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testbatch',
            name='args',
        ),
        migrations.RemoveField(
            model_name='testbatch',
            name='reruns',
        ),
        migrations.RemoveField(
            model_name='testbatch',
            name='reruns_delay',
        ),
    ]
