# Generated by Django 3.1.7 on 2021-04-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0080_auto_20210413_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenkinsreport',
            name='output',
        ),
    ]
