# Generated by Django 3.1.7 on 2021-04-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0081_remove_jenkinsreport_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreport',
            name='logfile',
            field=models.FileField(default='logs/pytest_error.log', upload_to='logs', verbose_name='日志文件'),
        ),
    ]
