# Generated by Django 3.1.7 on 2021-04-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0082_testreport_logfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsreport',
            name='logfile',
            field=models.FileField(default='jenkinslogs/pytest_error.log', upload_to='jenkinslogs', verbose_name='jenkins日志文件'),
        ),
    ]
