# Generated by Django 3.1.7 on 2021-04-16 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0083_jenkinsreport_logfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jenkinsreport',
            old_name='logfile',
            new_name='jenkinslogfile',
        ),
    ]
